# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [ ]:
import pandas as pd
url1 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df1 = pd.read_csv(url1)
df1.head()

In [ ]:
import pandas as pd
url2 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv"
df2 = pd.read_csv(url1)
df2.head()

In [ ]:
import pandas as pd
url3 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv"
df3 = pd.read_csv(url3)
df3.head()

In [72]:
def clean_cols(url):
    df = pd.read_csv(url)
    df.columns = df.columns.str.strip()
    df.rename(columns={"ST": "state"}, inplace=True)
    df.columns = df.columns.str.replace(" ", "_").str.lower()
    return df

url1 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
url2 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv"
url3 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv"

df1 = clean_cols(url1)
df2 = clean_cols(url2)
df3 = clean_cols(url3)

df_new = pd.concat([df1, df2, df3], ignore_index=True)

df_new.to_csv("customer_cleaned.csv", index=False)

def clean_rows(df):

    df["gender"] = df["gender"].replace({
        "Femal": "F",
        "female": "F",
        "Male": "M"
    })

    cat_cols = ["customer", "state", "gender", "education", "policy_type", "vehicle_class"]
    df[cat_cols] = df[cat_cols].fillna("Unknown")

    df["customer_lifetime_value"] = (df["customer_lifetime_value"].str.replace("%", "", regex=False).astype(float))
    df["number_of_open_complaints"] = (df["number_of_open_complaints"].str.split("/").str[1].fillna(0).astype(int))
    
    num_cols = ["customer_lifetime_value","income","monthly_premium_auto","total_claim_amount","number_of_open_complaints"]
    df[num_cols] = df[num_cols].fillna(df[num_cols].mean()).round()
    
    df["state"] = df["state"].replace({"Cali": "California","AZ": "Arizona","WA": "Washington"})
    df["education"] = df["education"].replace({"Bachelors": "Bachelor"})
    df["vehicle_class"] = df["vehicle_class"].replace({"Luxury SUV": "Luxury","Sports Car": "Luxury","Luxury Car": "Luxury"})

    return df


df_new = clean_rows(df_new)
df_new.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Unknown,Master,779946.0,0.0,1000.0,0,Personal Auto,Four-Door Car,3.0
1,QZ44356,Arizona,F,Bachelor,697954.0,0.0,94.0,0,Personal Auto,Four-Door Car,1131.0
2,AI49188,Nevada,F,Bachelor,1288743.0,48767.0,108.0,0,Personal Auto,Two-Door Car,566.0
3,WW63253,California,M,Bachelor,764586.0,0.0,106.0,0,Corporate Auto,SUV,530.0
4,GA49547,Washington,M,High School or Below,536308.0,36357.0,68.0,0,Personal Auto,Four-Door Car,17.0

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [7]:
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv"
df = pd.read_csv(url)
df.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

In [83]:
df.columns

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type', 'month'],
      dtype='object')

In [ ]:
rev_channel = pd.pivot_table(
    df,
    values="customer_lifetime_value",
    values="gender";
    index="sales_channel",
    aggfunc="sum"
).round(2)

total_revenue = rev_channel["customer_lifetime_value"].sum()

rev_channel["revenue_%"] = (rev_channel["customer_lifetime_value"] / total_revenue * 100).round()

rev_channel
#The Agent and Branch channels are the two most effective in terms of revenue. 
# The Agent channel generated 36% more revenue than the Branch channel.

               customer_lifetime_value  revenue_%
sales_channel
Agent                      33057887.85       38.0
Branch                     24359201.21       28.0
Call Center                17364288.37       20.0
Web                        12697632.90       15.0

In [24]:
average = pd.pivot_table(
    df,
    values="customer_lifetime_value",
    index="gender",         # rows
    columns="education",    # columns
    aggfunc="mean"
).round(2)

average

education  Bachelor  College   Doctor  High School or Below   Master
gender
F           7874.27  7748.82  7328.51               8675.22  8157.05
M           7703.60  8052.46  7415.33               8149.69  8168.83

In [26]:
pivot_sum = pd.pivot_table(
    df,
    values="customer_lifetime_value",
    index="gender",
    columns="education",
    aggfunc="sum"
)
pivot_pct = (pivot_sum / pivot_sum.values.sum() * 100).round(2)

pivot_pct

education  Bachelor  College  Doctor  High School or Below  Master
gender
F             15.30    14.24    1.68                 15.77    4.43
M             13.84    14.69    1.70                 14.50    3.85

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [28]:
df["number_of_open_complaints"].unique()

array([0, 3, 1, 2, 4, 5])

In [29]:
# Group by month and policy type, summing complaints
summary = (
    df.groupby(["month", "policy_type"])["number_of_open_complaints"]
    .sum()
    .reset_index()
)
summary.sort_values("number_of_open_complaints", ascending=False)

   month     policy_type  number_of_open_complaints
1      1   Personal Auto                       1635
4      2   Personal Auto                       1363
0      1  Corporate Auto                        415
3      2  Corporate Auto                        361
5      2    Special Auto                         91
2      1    Special Auto                         84